# Generated by Django 5.0.6 on 2024-06-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_listing_category_remove_listing_isactive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
