# Generated by Django 5.0.6 on 2024-06-17 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='Listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Listing', to='auctions.listing'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='startingbid',
            field=models.IntegerField(max_length=50),
        ),
    ]
