# Generated by Django 5.0.6 on 2024-06-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_bid_listing_alter_listing_startingbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='Category',
            field=models.CharField(default='appliances', max_length=50),
        ),
    ]
